Repository dukcode/ssafy-12th-gumi-02-algorithm-study, pull requests merged in 2024-09, with the labels that each got.

#150 [최재영 240901] 알고리즘 문제 풀이
  JY-CH/CT/c3-2.py
  JY-CH/CT/c3-3.py
  JY-CH/CT/c3-4.py
  JY-CH/SWEA/0831/s4875.py
Labels: 🔢문제

#149 [이성욱 240901] 알고리즘 문제 풀이
  hohnmb/백준 단어 길이 재기.py
  hohnmb/백준 문자열.py
  hohnmb/백준 숫자의합.py
  hohnmb/백준 아스키코드.py
Labels: 🔢문제

#148 [채용수 240901] 알고리즘 문제 풀이
  Yachaeyong/baekjoon/b11047.py
  Yachaeyong/baekjoon/b11399.py
  Yachaeyong/baekjoon/b13305.py
Labels: 3️⃣문제

#147 [전준표 240901] 알고리즘 문제 풀이
  junpyo0920/dongbin/greedy/1이_될_때까지.py
  junpyo0920/dongbin/greedy/숫자_카드_게임.py
  junpyo0920/dongbin/greedy/큰_수의_법칙.py
  junpyo0920/swea/10726.py
Labels: 🔢문제

#145 [서유민 240901] 알고리즘 문제 풀이
  sennaseo/algo_nadongbin/1이될때까지.py
  sennaseo/algo_nadongbin/거스름돈.py
  sennaseo/algo_nadongbin/숫자카드게임.py
  sennaseo/algo_nadongbin/큰수의법칙.py
Labels: 🔢문제

#146 [김덕윤 240901 240902] 알고리즘 문제 풀이
  dukcode/dongbin/greedy/1이_될_때까지.py
  dukcode/dongbin/greedy/거스름돈.py
  dukcode/dongbin/greedy/숫자_카드_게임.py
  dukcode/dongbin/greedy/큰_수의_법칙.py
Labels: 🔢문제

#156 [서유민 240902] 알고리즘 문제 풀이
  sennaseo/swea/1954_달팽이_숫자.py
Labels: 1️⃣문제

#155 [최재영 240902] 알고리즘 문제 풀이
  JY-CH/CT/c4-1.py
  JY-CH/CT/c4-2.py
  JY-CH/SWEA/0902/s4874.py
  JY-CH/SWEA/0902/s5188.py
  JY-CH/SWEA/0902/s5189.py
Labels: 🔢문제

#153 [채용수 240902] 알고리즘 문제 풀이
  Yachaeyong/baekjoon/b1541.py
  Yachaeyong/baekjoon/b1931.py
  Yachaeyong/codetest/Q1_모험가 길드.py
  Yachaeyong/codetest/Q2_곱하기_혹은_더하기.py
Labels: 🔢문제

#154 [이성욱 240902] 알고리즘 문제 풀이
  hohnmb/swea 돌뒤집기2.py
Labels: 1️⃣문제

#152 [김덕윤 240902] 알고리즘 문제 풀이
  dukcode/beakjoon/greedy/B1541.java
  dukcode/codetree/novice_mid/AddAllTheNumbersOnThePath.java
  dukcode/codetree/novice_mid/EqualizingTheHeightOfThrField.java
  dukcode/codetree/novice_mid/KeepTheLead3.java
  dukcode/codetree/novice_mid/SumCloseToParticularNumber.java
  dukcode/codetree/novice_mid/TheCapabilitiesOfTheDevelopmentTeam.java
  dukcode/swea/s1244_1.py
  dukcode/swea/s13063.py
  dukcode/swea/s13065.py
Labels: 🔢문제

#151 [전준표 240902] 알고리즘 문제 풀이
  junpyo0920/dongbin/greedy/곱하기_혹은_더하기.py
  junpyo0920/dongbin/greedy/모험가_길드.py
  junpyo0920/dongbin/greedy/문자열_뒤집기.py
Labels: 3️⃣문제

#162 [최재영 240903] 알고리즘 문제 풀이
  JY-CH/SWEA/0903/s5202.py
  JY-CH/SWEA/0903/s5203.py
Labels: 2️⃣문제

#159 [전준표 240903] 알고리즘 문제 풀이
  junpyo0920/baekjoon/b1026.py
  junpyo0920/baekjoon/b2217.py
  junpyo0920/swea/s13066.py
  junpyo0920/swea/s13067.py
  junpyo0920/swea/s13068.py
Labels: 🔢문제

#163 [최재영 240904] 알고리즘 문제 풀이
  JY-CH/SWEA/0904/s4880.py
  JY-CH/SWEA/0904/s4881.py
  JY-CH/SWEA/0904/s5201.py
Labels: 3️⃣문제

#164 [김덕윤 240906] 알고리즘 문제 풀이
  dukcode/codetree/intermediate_mid/FindNumberFast.java
  dukcode/codetree/intermediate_mid/FirstAppearNumber.java
  dukcode/codetree/intermediate_mid/NumberOfIntegers.java
  dukcode/codetree/intermediate_mid/PlayNumberGameWithComputer2.java
  dukcode/codetree/intermediate_mid/PointOnTheLineSegment.java
  dukcode/codetree/intermediate_mid/SumOfNNaturalNumbers.java
  dukcode/codetree/novice_mid/FindTheNumberOfPalindrome.java
  dukcode/codetree/novice_mid/TheGraceFromTeacher3.java
  dukcode/swea/s13112.py
  dukcode/swea/s13123.py
  dukcode/swea/s13124.py
  dukcode/swea/s13125.py
  dukcode/swea/s13125_1.py
  dukcode/swea/s13125_2.py
  dukcode/swea/s13126.py
  dukcode/swea/s14229.py
  dukcode/swea/s1865.py
Labels: 🔢문제

#165 [전준표 240906] 알고리즘 문제 풀이
  junpyo0920/baekjoon/b11399.py
  junpyo0920/baekjoon/b2457.py
  junpyo0920/swea/s13125.py
  junpyo0920/swea/s13126.py
  junpyo0920/swea/s1865.py
Labels: 🔢문제

#166 [서유민 240906] 알고리즘 문제 풀이
  sennaseo/beakjoon/2628_종이자르기.py
  sennaseo/swea/11671_ 기지국.py
  sennaseo/swea/1204_최빈수_구하기.py
  sennaseo/swea/1974_스도쿠_검증.py
  sennaseo/swea/20397_돌_뒤집기_게임_2.py
  sennaseo/swea/2805_농작물_수확하기.py
  sennaseo/월말과목평가/같은_모양_찾기.py
  sennaseo/월말과목평가/평지_만들기.py
Labels: 🔢문제

#167 [채용수 240906] 알고리즘 문제 풀이
  Yachaeyong/codetest/Q5_볼링공 고르기.py
  Yachaeyong/swea/s13126.py
  Yachaeyong/swea/s1859.py
  Yachaeyong/swea/s20551.py
  Yachaeyong/swea/s22372.py
Labels: 🔢문제

#168 [이성욱 240906] 알고리즘 문제 풀이
  hohnmb/색종이.py
  hohnmb/세로읽기.py
  hohnmb/스위치 조작.py
  hohnmb/최댓값 asshole.py
  hohnmb/행렬덧셈 레츠고.py
Labels: 🔢문제

#174 [전준표 240908] 알고리즘 문제 풀이
  junpyo0920/swea/s5656.py
Labels: 1️⃣문제

#173 [최재영 240908] 알고리즘 문제 풀이
  JY-CH/CT/c5-3.py
  JY-CH/SWEA/0908/s22375.py
  JY-CH/SWEA/0908/s5208.py
Labels: 2️⃣문제

#172 [이성욱 240908] 알고리즘 문제 풀이
  hohnmb/im 스위치 조작.py
  hohnmb/스도쿠검증.py
Labels: 2️⃣문제

#171 [김덕윤 240908] 알고리즘 문제 풀이
  dukcode/codetree/intermediate_mid/AscendingOrderOfTowDimensionalArray.java
  dukcode/codetree/intermediate_mid/DistributingIntegers.java
  dukcode/codetree/intermediate_mid/ThreeFiveMoo.java
Labels: 3️⃣문제

#170 [서유민 240908] 알고리즘 문제 풀이
  sennaseo/swea/1859_백만_장자_프로젝트.py
Labels: 2️⃣문제

#169 [채용수 240908] 알고리즘 문제 풀이
  Yachaeyong/swea/s1856.py
  Yachaeyong/swea/s1865.py
  Yachaeyong/swea/s5208.py
  Yachaeyong/swea/s5209.py
Labels: 3️⃣문제

#179 [전준표 240909] 알고리즘 문제 풀이
  junpyo0920/swea/s12741.py
  junpyo0920/swea/s20551.py
  junpyo0920/swea/s4008.py
  junpyo0920/swea/s5656_2.py
Labels: 🔢문제

#177 [김덕윤 240909] 알고리즘 문제 풀이
  dukcode/codetree/intermediate_mid/MaximizeDistOfNearestPoints.java
  dukcode/codetree/intermediate_mid/MaximumDistancePoint.java
  dukcode/codetree/intermediate_mid/MaximumTransitTime.java
  dukcode/codetree/intermediate_mid/NPeopleWIthNumbers.java
  dukcode/codetree/intermediate_mid/PaintingTheGrid2.java
  dukcode/codetree/intermediate_mid/TwoPointsOfTheLineThatDontOverlap.java
  dukcode/swea/s1767.py
Labels: 🔢문제

#175 [이성욱 240909] 알고리즘 문제 풀이
  hohnmb/anywhere.py
  hohnmb/carrot.py
Labels: 2️⃣문제

#176 [최재영 240909] 알고리즘 문제 풀이
  JY-CH/CT/c5-3-2.py
  JY-CH/CT/c5-3.py
  JY-CH/SWEA/0909/s12712.py
  JY-CH/SWEA/0909/s12741.py
  JY-CH/SWEA/0909/s20551.py
Labels: 🔢문제

#178 [서유민 240909] 알고리즘 문제 풀이
  sennaseo/IM/240909_IM.py
  sennaseo/swea/13732_정사각형_판정.py
  sennaseo/swea/4613_러시아_국기_같은_깃발.py
Labels: 3️⃣문제

#180 [채용수 240909] 알고리즘 문제 풀이
  Yachaeyong/swea/IM_test.py
Labels: 1️⃣문제

#181 [김덕윤 240910] 알고리즘 문제 풀이
  dukcode/swea/s1767_1.py
Labels: 1️⃣문제

#182 [최재영 240910] 알고리즘 문제 풀이
  JY-CH/CT/c5-4.py
  JY-CH/SWEA/0910/s10580.py
  JY-CH/SWEA/0910/s20739.py
  JY-CH/SWEA/0910/s3499.py
  JY-CH/baekjoon/B2557.java
Labels: 🔢문제

#183 [채용수 240910] 알고리즘 문제 풀이
  Yachaeyong/codetest/게임개발.py
  Yachaeyong/codetest/상하좌우.py
  Yachaeyong/codetest/시각.py
  Yachaeyong/codetest/왕실의 나이트.py
  Yachaeyong/swea/s13173.py
  Yachaeyong/swea/s13714.py
  Yachaeyong/swea/s7465.py
Labels: 🔢문제

#184 [이성욱 240910] 알고리즘 문제 풀이
  hohnmb/binary_tree_ex.py
Labels: 1️⃣문제

#186 [서유민 240911] 알고리즘 문제 풀이
  sennaseo/algo_nadongbin/미로_탈출.py
  sennaseo/algo_nadongbin/음료수_얼려_먹기.py
Labels: 2️⃣문제

#187 [김덕윤 240912] 알고리즘 문제 풀이
  dukcode/codetree/intermediate_mid/DropTheBomb.java
  dukcode/codetree/intermediate_mid/MoveToTheColoredSpaceOnly2.java
Labels: 2️⃣문제

#189 [채용수 240912] 알고리즘 문제 풀이
  Yachaeyong/swea/s1238.py
  Yachaeyong/swea/s1249.py
Labels: 2️⃣문제

#190 [최재영 240912] 알고리즘 문제 풀이
  JY-CH/CT/c4-2.py
  JY-CH/CT/c4-ex1.py
  JY-CH/CT/c4-ex2.py
  JY-CH/SWEA/0912/s1222.py
Labels: 2️⃣문제

#191 [전준표 240912] 알고리즘 문제 풀이
  junpyo0920/baekjoon/b1197.py
  junpyo0920/baekjoon/b1197_2.py
Labels: 1️⃣문제

#196 [최재영 240918] 알고리즘 문제 풀이
  JY-CH/SWEA/0918/s1223.py
Labels: 1️⃣문제

#202 [김덕윤 240923] 알고리즘 문제 풀이
  dukcode/beakjoon/b2557.py
  dukcode/beakjoon/mst/B17472.java
Labels: 1️⃣문제

#204 [서유민 240923] 알고리즘 문제 풀이
  sennaseo/swea/1210_Ladder1.py
  sennaseo/swea/5248_그룹_나누기.py
Labels: 1️⃣문제

#203 [최재영 240923] 알고리즘 문제 풀이
  JY-CH/SWEA/0919/s5105.py
Labels: 1️⃣문제

#200 [이성욱 240923] 알고리즘 문제 풀이
  hohnmb/고대유적1.py
Labels: 1️⃣문제

#201 [채용수 240923] 알고리즘 문제 풀이
  Yachaeyong/codetest/미로 탈출.py
  Yachaeyong/codetest/음료수 얼려 먹기.py
  Yachaeyong/swea/s1251_1.py
  Yachaeyong/swea/s1251_2.py
  Yachaeyong/swea/s1795.py
Labels: 2️⃣문제

#199 [전준표 240923] 알고리즘 문제 풀이
  junpyo0920/baekjoon/b12166.py
  junpyo0920/baekjoon/b17472.py
  junpyo0920/baekjoon/b1753.py
  junpyo0920/baekjoon/b1774.py
  junpyo0920/baekjoon/b4386.py
Labels: 2️⃣문제

#209 [채용수 240924] 알고리즘 문제 풀이
  Yachaeyong/codetest/특정 거리의 도시 찾기.py
Labels: 1️⃣문제

#208 [이성욱 240924] 알고리즘 문제 풀이
  hohnmb/달팽이 숫자.py
  hohnmb/연속한 1의 갯수.py
Labels: 1️⃣문제

#207 [전준표 240924] 알고리즘 문제 풀이
  junpyo0920/baekjoon/b4179.py
Labels: 1️⃣문제

#206 [김덕윤 240924] 알고리즘 문제 풀이
  dukcode/beakjoon/union_find/B1717.java
Labels: 1️⃣문제

#214 [최재영 240926] 알고리즘 문제 풀이
  JY-CH/SWEA/0926/s5099.py
Labels: 1️⃣문제

#213 [이성욱 240926] 알고리즘 문제 풀이
  hohnmb/우주선 착륙2.py
Labels: 1️⃣문제

#212 [김덕윤 240926] 알고리즘 문제 풀이
  dukcode/beakjoon/B14999.java
Labels: 1️⃣문제

#211 [채용수 240926] 알고리즘 문제 풀이
  Yachaeyong/codetest/1로 만들기.py
  Yachaeyong/codetest/피보나치.py
Labels: 2️⃣문제

#210 [서유민 240926] 알고리즘 문제 풀이
  sennaseo/swea/4861_회문.py
Labels: 1️⃣문제

#219 [전준표 240927] 알고리즘 문제 풀이
  junpyo0920/baekjoon/b1717.py
  junpyo0920/baekjoon/b1976.py
Labels: 2️⃣문제

#218 [서유민 240927] 알고리즘 문제 풀이
  sennaseo/swea/4864_문자열_비교.py
Labels: 1️⃣문제

#215 [채용수 240927] 알고리즘 문제 풀이
  Yachaeyong/codetest/개미 전사.py
Labels: 1️⃣문제

#216 [이성욱 240927] 알고리즘 문제 풀이
  hohnmb/공과 잡초.py
Labels: 1️⃣문제

#217 [최재영 240927] 알고리즘 문제 풀이
  JY-CH/baekjoon/b2178.py
Labels: 1️⃣문제

#224 [전준표 240929] 알고리즘 문제 풀이
  junpyo0920/baekjoon/b1463.py
  junpyo0920/baekjoon/b24416.py
Labels: 2️⃣문제

#223 [이성욱 240929] 알고리즘 문제 풀이
  hohnmb/종이붙이기.py
Labels: 1️⃣문제

#222 [채용수 240929] 알고리즘 문제 풀이
  Yachaeyong/baekjoon/b9461.py
Labels: 1️⃣문제

#221 [서유민 240929] 알고리즘 문제 풀이
  sennaseo/swea/1221_GNS.py
Labels: 1️⃣문제

#220 [김덕윤 240929] 알고리즘 문제 풀이
  dukcode/codetree/novice_mid/radix/TransformationOfNumberSystem.java
  dukcode/codetree/novice_mid/sorting/IncDecSorting.java
  dukcode/codetree/novice_mid/sorting/IndicesOfSortedArray.java
  dukcode/codetree/novice_mid/sorting/StringSort.java
Labels: 🔢문제
